---
version: 2

updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "04:00"
    labels:
      - "pip"
      - "dependencies"
    reviewers:
      - "plcnk"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "10:00"
      reviewers:
        - "plcnk"
