from os import getenv

BEARER_TOKEN = getenv("TWITTER_BEARER_TOKEN")
API_KEY = getenv("TWITTER_API_KEY")
API_KEY_SECRET = getenv("TWITTER_API_KEY_SECRET")
ACCESS_TOKEN = getenv("TWITTER_ACCESS_TOKEN")
ACCESS_TOKEN_SECRET = getenv("TWITTER_ACCESS_TOKEN_SECRET")
