name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: psf/black@stable
        with:
          options: "-l 120 --check"
          src: "./"
          version: "22.6.0"
